### ISSUE TITLE
General - Decouple test user data

### ISSUE THREAD

**Issue by liampalmer0** [liampalmer0/fit-of-the-day#95]
# Hard Coded User Data Calls
Currently every user has the same data because it's hard coded to get test data
Find all places where test data is called and add actual calls to user data (need to handle empty results; see #96)

#### Some places to fix :
- [ ] Article image paths (#67, #181)

### Handled by #129 
- [x] Filtering Closet (#90)
### Handled by #118
- [x] Deleting article (#33)
### Handled by #117
- [x] Getting all articles on closet page (#49)
- [x] Getting article details (#69)
- [x] Editing article (#30)
- [x] Generating random recommendations (#74)
- [x] Filtering random recommendations
